# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4766c7ee6f68be0e390d884bd9d751c0112a83eb77df7d147c76c76044de434e4dca800c593c051dba6136d158a20a7011497e2cd3cad2766f76e84cbd33e2d3

test:
  secret_key_base: 893f8e750cc9776704a292c2899311eb704f502fe7e4382f2af9a4b3132b7d2d63244b21b4254f7f456ffc5cdec2964c154029b63ffaa073b3a87f9f2249a4d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
